
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
logoFile="pmm2_banner_0.1.7.png"
displayName="${mod_name}"
authors="${mod_authors}"
credits="${mod_authors}"
description='''${mod_description}'''
issueTrackerURL="https://github.com/dododoshirouto/PeopleMobsMod2/issues"
displayURL="https://github.com/dododoshirouto/PeopleMobsMod2"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"